workflows:
  ios_build:
    name: Build and Test iOS
    environment:
      flutter: stable
      xcode: "14.3"  # Make sure the Xcode version matches the required one for your project
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Upgrade dependencies
        script: |
          flutter pub upgrade
      - name: Clear pub cache
        script: |
          flutter pub cache repair
      - name: Clean build
        script: |
          flutter clean
      - name: Ensure iOS platform is included
        script: |
          if [ ! -d "ios" ]; then
            flutter create --platform ios .
          fi
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.app.dSYM
    publishing:
      artifacts:
        - build/ios/iphoneos/Runner.ipa
