workflows:
  ios_build:
    name: Build and Test iOS
    environment:
      flutter: stable
      xcode: "15"  # Update this to match the required Xcode version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Add iOS platform
        script: |
          if [ ! -d "ios" ]; then
            flutter create --platform ios .
          fi
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.app.dSYM